default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: mysecretpassword

development:
  <<: *default
  database: kurzy_development

test:
  <<: *default
  database: kurzy_test

production:
  primary:
    adapter: postgresql
    encoding: unicode
